name: my_plugin_android01
description: my android plugin 01
version: 0.0.2
homepage: https://github.com/krijk/

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.linknext.my_plugin_android01
        pluginClass: MyPluginAndroid01Plugin
