name: my_plugin_android01
description: my android plugin 01
version: 0.0.7
homepage: https://github.com/krijk/

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.linknext.my_plugin_android01
        pluginClass: MyPluginAndroid01Plugin
